#cloud-config
write_files:
- encoding: gzip
  content: !!binary |
      ${docker-compose}
  path: /root/docker-compose.yml
  permissions: '0755'
mounts:
- [ ${volume_path}, /mnt/MC-world, auto, "discard,defaults" ]
runcmd:
    - cd /root; docker compose up -d